# Generated by Django 3.0 on 2021-03-17 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0003_auto_20210317_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redacción',
            name='fecha',
            field=models.DateField(blank=True),
        ),
    ]
